# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: some-postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example

  adminer:
    image: some-silverpeas
    restart: always
    ports:
      - 8080:8080